### ISSUE TITLE
lipo: can't open input file in xcode 6.2

### ISSUE THREAD

**Issue by gigq** [syshen/Embedded-Framework-Demo#2]
The following build commands failed:
    Check dependencies
(1 failure)
cp: /Users/justin/Library/Developer/Xcode/DerivedData/SwiftFramework-bkkmbwlecpnoxxhdzllyyssnymdp/Build/Products/Debug-iphoneos/SwiftFramework.framework/.: No such file or directory

fatal error: lipo: can't open input file: /Users/justin/Library/Developer/Xcode/DerivedData/SwiftFramework-bkkmbwlecpnoxxhdzllyyssnymdp/Build/Products/Debug-iphoneos/SwiftFramework.framework/SwiftFramework (No such file or directory)

**Comment by odemolliens** [comment]
Fixed in Pull request #3
